if: commit_message =~ /\[publish binaries\]/

branches:
  only:
  - master
  - /^[vV]\d+\.\d+(\.\d+)?(-\S*)?$/

language: cpp

cache:
  directories:
  - $HOME/Library/Caches/Homebrew
  - qwt
  - D2XX
  - site-packages
  - VLC
  - src/GoldenCheetah.app

env:
  global:
  - BRANCH=master

jobs:
  include:
  - os: osx
    osx_image: xcode11.3
    compiler: clang
  - os: linux
    dist: bionic
    compiler: gcc

before_install:
- travis/$TRAVIS_OS_NAME/before_install.sh

before_script:
- travis/$TRAVIS_OS_NAME/before_script.sh

script:
- travis/$TRAVIS_OS_NAME/script.sh

before_cache:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew cleanup; fi

after_success:
- travis/$TRAVIS_OS_NAME/after_success.sh
